config/routes.rb
Rails.application.routes.draw do

  root to: 'tasks#index'
  
  get 'signin', to: 'users#new'
  
  get 'login' , to: 'sessions#new'
  post 'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :tasks
  resources :users, only: [:new,:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 }
  validates :status, presence: true, length: { maximum: 10 }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  
  has_secure_password
  
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  
  private
  
  def login(email,password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only:[:show,:edit,:update,:destroy]

  def index
    @tasks = current_user.tasks.order(id: :asc).page(params[:page]).per(5)
  end
  
  def show
  end
  
  def new
    @task = current_user.tasks.new
  end
  
  def create
    @task= current_user.tasks.new(task_param)
    if @task.save
      flash[:success] = 'タスクの登録が完了しました'
      redirect_to tasks_url
    else
      flash[:danger] = 'タスクの登録に失敗しました'
      render :new
    end
  end
  
  def edit
  end
  
  def update
    
    if @task.update(task_param)
      flash[:success] = 'タスクの登録が完了しました'
      redirect_to @task
    else
      flash[:danger] = 'タスクの登録に失敗しました'
      render :edit
    end
  end
  
  def destroy
    @task.destroy
    flash[:success] = 'タスクを削除しました'
    redirect_to tasks_url
  end
  
  
  private
  def task_param
    params.require(:task).permit(:content , :status)
  end
  
  
  def correct_user
    @task= current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = '登録が完了しました'
      redirect_to tasks_path
    else
      flash[:danger] = '登録に失敗しました'
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
 <ul>
   <% model.errors.full_messages.each do |message| %>
   <li><%= message %></li>
   <% end %>
 </ul>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type,message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class ="container">
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local:true) do |f| %>
 <%= render 'layouts/error_messages',model: f.object %>
  <p>
    <%= f.label :content,'メッセージ'%>
    <%= f.text_field :content %>
  </p>
  <p>
    <%= f.label :status,'進捗度'%>
    <%= f.text_field :status %>
  </p>
  <%= f.submit '登録'%>
<% end %>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id %>のタスク編集ページ</h1>

<%= render 'form', task: @task %>
<%= link_to '戻る', @task %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<ul>
  <% @tasks.each do |task| %>
  <li>
    <%= link_to task.id , task %> :  <%= task.content %> -- 進捗度: <%= task.status %>
  </li>
  <% end %>
</ul>

<%= link_to '新規タスクの登録', new_task_path %>

<div>
  <%= link_to 'ログアウト' ,logout_path , method: :delete %>
</div>

app/views/tasks/new.html.erb
<h1>タスク登録ページ</h1>

<%= render 'form', task: @task %>

<%= link_to '一覧に戻る',tasks_path %>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id%> のタスク情報</h1>

<p><%= @task.content %></p>
<p>進捗状況：<%= @task.status %></p>

<%= link_to 'タスクの編集',edit_task_path%>
<%= link_to 'タスクの削除',@task , method: :delete, data:{ confirm: '削除します。よろしいですか'} %>
<%= link_to '戻る',tasks_path%>

app/views/users/new.html.erb
<h1>新規会員登録</h1>
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'layouts/error_messages' , model: f.object %>
  <div class = "form-group">
    <%= f.label :name, 'Name：' %>
    <%= f.text_field :name %>
  </div>
  <div class = "form-group">
    <%= f.label :email, 'Emai：' %>
    <%= f.text_field :email %>
  </div>
  <div class = "form-group">
    <%= f.label :password, 'Password：' %>
    <%= f.password_field :password %>
  </div>
  <div class = "form-group">
    <%= f.label :password_confirmation, '確認パスワード：' %>
    <%= f.password_field :password_confirmation %>
  </div>
  
  <%= f.submit '登録'%>
<% end %>

<%= link_to '戻る', login_path %>